// takussan-web/src/components/properties/PropertyCard.tsx
import Image from 'next/image';
import Link from 'next/link';
import type { PropertyListItem } from '@/types/property';

function formatPrice(price: number): string {
  return new Intl.NumberFormat('fr-SN', {
    style: 'currency',
    currency: 'XOF',
    maximumFractionDigits: 0,
  }).format(price);
}

export function PropertyCard({ property }: { property: PropertyListItem }) {
  const photo = property.main_photo_url
    ?? 'https://placehold.co/800x533/e7e5e4/a8a29e?text=Photo+%C3%A0+venir';

  return (
    <Link href={`/properties/${property.slug}`} className="group block">
      <article className="bg-white rounded-xl shadow-sm overflow-hidden hover:shadow-md transition-shadow duration-150">
        <div className="relative aspect-[4/3] bg-stone-200">
          <Image
            src={photo}
            alt={property.title}
            fill
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
            className="object-cover group-hover:scale-105 transition-transform duration-300"
          />
          {property.featured && (
            <span className="absolute top-3 left-3 bg-slate-700 text-white text-xs font-medium px-2 py-1 rounded-full">
              À la une
            </span>
          )}
        </div>

        <div className="p-4">
          <p className="text-xs text-stone-500 mb-1">
            {property.type} · {property.location.quarter}
          </p>
          <h2 className="font-semibold text-stone-900 leading-snug mb-2 line-clamp-2 group-hover:text-slate-700 transition-colors duration-150">
            {property.title}
          </h2>

          <div className="flex items-center gap-3 text-sm text-stone-600 mb-3">
            {property.bedrooms && <span>{property.bedrooms} ch.</span>}
            {property.area && <span>{property.area} m²</span>}
          </div>

          <p className="text-lg font-bold text-slate-800">
            {formatPrice(property.price)}
          </p>
        </div>
      </article>
    </Link>
  );
}

// src/app/shared/components/product-card/property-card.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {CommonModule} from '@angular/common';
import {Property} from "../../../core/models/http/property.model";
import {Media} from "../../../core/models/http/media.model";

@Component({
  selector: 'app-property-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './property-card.component.html',
  styleUrls: ['./property-card.component.scss']
})
export class PropertyCardComponent {
  @Input() property!: Property;
  @Input() isFavorite = false;

  @Output() propertyClick = new EventEmitter<Property>();
  @Output() favoriteToggle = new EventEmitter<any>();
  @Output() scheduleVisit = new EventEmitter<Property>();
  @Output() chat = new EventEmitter<Property>();

  get images(): Media[] {
    this.property.media = this.property.media || [];
    return this.property.media.filter((media) => media.mime_type?.includes('image'))
  }

  get featuredImageUrl(): string {
    if (this.images?.length) {
      return this.images[0].preview_url!
    }
    return '';
  }

  get formatedPrice(): string {
    const price = this.property.price;
    if (!price) return '0';
    return new Intl.NumberFormat('fr-FR').format(price);
  }

}


<div class="group cursor-pointer">
    <!-- Property Card (same structure as above) -->
    <div class="relative">
        <div class="relative aspect-square rounded-xl overflow-hidden bg-gray-200 shadow-sm">
            <img
                    [alt]="property.title"
                    [src]="featuredImageUrl"
                    class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">

            <button class="absolute top-3 right-3 p-2 rounded-full bg-white/80 hover:bg-white transition-colors">
                <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor"
                     viewBox="0 0 24 24">
                    <path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
                          stroke-linecap="round" stroke-linejoin="round"
                          stroke-width="2"></path>
                </svg>
            </button>

            <div class="absolute top-3 left-3">
              <span class="px-3 py-1 bg-white/90 backdrop-blur-sm rounded-full text-xs font-medium text-gray-900">
                {{ property.contract_type === 'sale' ? 'Vente' : 'Location' }}
              </span>
            </div>
        </div>

        <div class="mt-1.5">
            <div class="flex items-start justify-between">
                <div class="flex-1">
                    <h3 class="font-medium text-gray-900 line-clamp-1">{{ property.title }}</h3>
                    <p class="text-sm text-gray-500">
                        {{ property.area }} m²
                    </p>
                </div>
            </div>
            <div class="">
                <span class="font-semibold text-gray-900">{{ formatedPrice }} FCFA</span>
                <span *ngIf="property.contract_type === 'rent'"
                      class="text-sm text-gray-500"> /mois</span>
            </div>
        </div>
    </div>
</div>
