// takussan-web/src/components/PropertyCard.tsx
'use client';

import React from 'react';
import Image from 'next/image';
import { Heart, MapPin } from 'lucide-react';
import type { Property } from '@/data/mockData';

export interface PropertyCardProps {
  readonly property: Property;
  readonly className?: string;
}

export function PropertyCard({ property, className }: PropertyCardProps) {
  const isSale = property.transaction === 'sale';

  return (
    <div className={`group cursor-pointer ${className || ''}`}>
      {/* Image Container */}
      <div className="relative aspect-4/3 rounded-xl overflow-hidden mb-5">
        <Image
          src={property.image}
          alt={property.title}
          fill
          className="object-cover group-hover:scale-105 transition-transform duration-500"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw"
        />

        {/* Transaction Badge */}
        <div
          className={`absolute top-4 left-4 text-white text-[10px] font-bold uppercase tracking-wider px-3 py-1.5 rounded-full shadow-md ${
            isSale ? 'bg-[#0050cb]' : 'bg-[#2e7d32]'
          }`}
        >
          {isSale ? 'En Vente' : 'En Location'}
        </div>

        {/* Favorite Button */}
        <button className="absolute top-4 right-4 w-10 h-10 rounded-full bg-white/20 backdrop-blur-md flex items-center justify-center text-white hover:bg-white hover:text-[#0050cb] transition-colors">
          <Heart className="w-5 h-5" />
        </button>
      </div>

      {/* Content */}
      <div className="space-y-2">
        <h3 className="font-bold text-lg text-gray-900">{property.title}</h3>
        <p className="text-[#0050cb] font-bold">{property.price}</p>
        <p className="text-gray-500 text-sm flex items-center gap-1">
          <MapPin className="w-4 h-4" />
          {property.location}
        </p>
        <div className="flex items-center gap-4 pt-2 text-xs font-semibold text-gray-400">
          {property.bedrooms > 0 && (
            <>
              <span>{property.bedrooms} Ch.</span>
              <span className="w-1 h-1 bg-gray-300 rounded-full" />
            </>
          )}
          <span>{property.surface}</span>
          <span className="w-1 h-1 bg-gray-300 rounded-full" />
          <span>{property.feature}</span>
        </div>
      </div>
    </div>
  );
}

// src/app/shared/components/product-card/property-card.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {CommonModule} from '@angular/common';
import {Property} from "../../../core/models/http/property.model";
import {Media} from "../../../core/models/http/media.model";

@Component({
  selector: 'app-property-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './property-card.component.html',
  styleUrls: ['./property-card.component.scss']
})
export class PropertyCardComponent {
  @Input() property!: Property;
  @Input() isFavorite = false;

  @Output() propertyClick = new EventEmitter<Property>();
  @Output() favoriteToggle = new EventEmitter<any>();
  @Output() scheduleVisit = new EventEmitter<Property>();
  @Output() chat = new EventEmitter<Property>();

  get images(): Media[] {
    this.property.media = this.property.media || [];
    return this.property.media.filter((media) => media.mime_type?.includes('image'))
  }

  get featuredImageUrl(): string {
    if (this.images?.length) {
      return this.images[0].preview_url!
    }
    return '';
  }

  get formatedPrice(): string {
    const price = this.property.price;
    if (!price) return '0';
    return new Intl.NumberFormat('fr-FR').format(price);
  }

}


<div class="group cursor-pointer">
    <!-- Property Card (same structure as above) -->
    <div class="relative">
        <div class="relative aspect-square rounded-xl overflow-hidden bg-gray-200 shadow-sm">
            <img
                    [alt]="property.title"
                    [src]="featuredImageUrl"
                    class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">

            <button class="absolute top-3 right-3 p-2 rounded-full bg-white/80 hover:bg-white transition-colors">
                <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor"
                     viewBox="0 0 24 24">
                    <path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
                          stroke-linecap="round" stroke-linejoin="round"
                          stroke-width="2"></path>
                </svg>
            </button>

            <div class="absolute top-3 left-3">
              <span class="px-3 py-1 bg-white/90 backdrop-blur-sm rounded-full text-xs font-medium text-gray-900">
                {{ property.contract_type === 'sale' ? 'Vente' : 'Location' }}
              </span>
            </div>
        </div>

        <div class="mt-1.5">
            <div class="flex items-start justify-between">
                <div class="flex-1">
                    <h3 class="font-medium text-gray-900 line-clamp-1">{{ property.title }}</h3>
                    <p class="text-sm text-gray-500">
                        {{ property.area }} m²
                    </p>
                </div>
            </div>
            <div class="">
                <span class="font-semibold text-gray-900">{{ formatedPrice }} FCFA</span>
                <span *ngIf="property.contract_type === 'rent'"
                      class="text-sm text-gray-500"> /mois</span>
            </div>
        </div>
    </div>
</div>
