// src/app/shared/components/property-card/property-card.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {CommonModule} from '@angular/common';
import {Property} from "../../../core/models/http/property.model";
import {Media} from "../../../core/models/http/media.model";
import {LucideAngularModule, MapPin, Bed, Bath, Maximize, Heart, Calendar, ArrowRight} from 'lucide-angular';
import {BadgeComponent} from "../badge/badge.component";
import {PriceFormatPipe} from "../../pipes/price-format.pipe";
import {AreaFormatPipe} from "../../pipes/area-format.pipe";

@Component({
  selector: 'app-property-card',
  standalone: true,
  imports: [
    CommonModule,
    LucideAngularModule,
    BadgeComponent,
    PriceFormatPipe,
    AreaFormatPipe
  ],
  templateUrl: './property-card.component.html'
})
export class PropertyCardComponent {
  @Input() property!: Property;
  @Input() isFavorite = false;
  @Input() viewMode: 'grid' | 'list' = 'grid';

  @Output() propertyClick = new EventEmitter<Property>();
  @Output() favoriteToggle = new EventEmitter<any>();
  @Output() scheduleVisit = new EventEmitter<Property>();
  @Output() chat = new EventEmitter<Property>();

  // Icons
  readonly MapPin = MapPin;
  readonly Bed = Bed;
  readonly Bath = Bath;
  readonly Maximize = Maximize;
  readonly Heart = Heart;
  readonly Calendar = Calendar;
  readonly ArrowRight = ArrowRight;

  get images(): Media[] {
    this.property.media = this.property.media || [];
    return this.property.media.filter((media) => media.mime_type?.includes('image'))
  }

  get featuredImageUrl(): string {
    if (this.images?.length) {
      return this.images[0].preview_url!
    }
    return '';
  }
}


<!-- Grid View -->
@if (viewMode === 'grid') {
    <div (click)="propertyClick.emit(property)"
         class="group cursor-pointer bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700 overflow-hidden hover:shadow-lg hover:border-blue-100 dark:hover:border-blue-900 transition-all duration-300 h-full flex flex-col">

        <!-- Image Container -->
        <div class="relative aspect-[4/3] overflow-hidden bg-gray-100 dark:bg-gray-700">
            <img [alt]="property.title"
                 [src]="featuredImageUrl || 'https://placehold.co/600x400?text=No+Image'"
                 class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500">

            <!-- Overlay Gradient -->
            <div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>

            <!-- Badges -->
            <div class="absolute top-3 left-3 flex gap-2">
                <app-badge [variant]="property.contract_type === 'sale' ? 'primary' : 'secondary'" size="sm" [rounded]="true">
                    {{ property.contract_type === 'sale' ? 'Vente' : 'Location' }}
                </app-badge>
                @if (property.status === 'sold' || property.status === 'rented') {
                    <app-badge variant="danger" size="sm" [rounded]="true">
                        {{ property.status === 'sold' ? 'Vendu' : 'Loué' }}
                    </app-badge>
                }
            </div>

            <!-- Favorite Button -->
            <button (click)="$event.stopPropagation(); favoriteToggle.emit(property)"
                    class="absolute top-3 right-3 p-2 rounded-full bg-white/90 dark:bg-gray-800/90 hover:bg-white dark:hover:bg-gray-700 transition-all shadow-sm active:scale-95">
                <lucide-icon [img]="Heart" [class.fill-red-500]="isFavorite" [class.text-red-500]="isFavorite"
                             class="w-4 h-4 text-gray-600 dark:text-gray-300"></lucide-icon>
            </button>
        </div>

        <!-- Content -->
        <div class="p-4 flex flex-col flex-1">
            <!-- Price & Address -->
            <div class="mb-3">
                <div class="flex items-center justify-between mb-1">
                    <span class="text-xl font-bold text-gray-900 dark:text-white">
                        {{ property.price | priceFormat }}
                        @if (property.contract_type === 'rent') {
                            <span class="text-xs font-normal text-gray-500">/mois</span>
                        }
                    </span>
                </div>
                <h3 class="font-medium text-gray-900 dark:text-white line-clamp-1 group-hover:text-blue-600 transition-colors">
                    {{ property.title }}
                </h3>
                <div class="flex items-center gap-1 text-sm text-gray-500 dark:text-gray-400 mt-1">
                    <lucide-icon [img]="MapPin" class="w-3 h-3"></lucide-icon>
                    <span class="truncate">{{ property.address?.city || 'Dakar' }}, {{ property.address?.address || 'Adresse non spécifiée' }}</span>
                </div>
            </div>

            <!-- Features -->
            <div class="flex items-center gap-4 py-3 border-t border-gray-100 dark:border-gray-700 mt-auto">
                <div class="flex items-center gap-1.5 text-sm text-gray-600 dark:text-gray-400" title="Chambres">
                    <lucide-icon [img]="Bed" class="w-4 h-4"></lucide-icon>
                    <span class="font-medium">{{ property.metadata?.['bedrooms'] || 0 }}</span>
                </div>
                <div class="flex items-center gap-1.5 text-sm text-gray-600 dark:text-gray-400" title="Salles de bain">
                    <lucide-icon [img]="Bath" class="w-4 h-4"></lucide-icon>
                    <span class="font-medium">{{ property.metadata?.['bathrooms'] || 0 }}</span>
                </div>
                <div class="flex items-center gap-1.5 text-sm text-gray-600 dark:text-gray-400" title="Surface">
                    <lucide-icon [img]="Maximize" class="w-4 h-4"></lucide-icon>
                    <span class="font-medium">{{ property.area | areaFormat }}</span>
                </div>
            </div>
        </div>
    </div>
}

<!-- List View -->
@if (viewMode === 'list') {
    <div (click)="propertyClick.emit(property)"
         class="group cursor-pointer bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700 overflow-hidden hover:shadow-md hover:border-blue-100 dark:hover:border-blue-900 transition-all duration-300">
        <div class="flex flex-col sm:flex-row h-full">
            <!-- Image Section -->
            <div class="relative sm:w-72 min-h-[200px] sm:min-h-full flex-shrink-0 bg-gray-100 dark:bg-gray-700 overflow-hidden">
                <img [alt]="property.title"
                     [src]="featuredImageUrl || 'https://placehold.co/600x400?text=No+Image'"
                     class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500">

                <div class="absolute top-3 left-3 flex gap-2">
                    <app-badge [variant]="property.contract_type === 'sale' ? 'primary' : 'secondary'" size="sm" [rounded]="true">
                        {{ property.contract_type === 'sale' ? 'Vente' : 'Location' }}
                    </app-badge>
                </div>

                <button (click)="$event.stopPropagation(); favoriteToggle.emit(property)"
                        class="absolute top-3 right-3 p-2 rounded-full bg-white/90 dark:bg-gray-800/90 hover:bg-white transition-all shadow-sm active:scale-95">
                    <lucide-icon [img]="Heart" [class.fill-red-500]="isFavorite" [class.text-red-500]="isFavorite"
                                 class="w-4 h-4 text-gray-600 dark:text-gray-300"></lucide-icon>
                </button>
            </div>

            <!-- Content Section -->
            <div class="flex-1 p-5 flex flex-col">
                <div class="flex justify-between items-start mb-2">
                    <div>
                        <div class="flex items-center gap-2 mb-1">
                            <span class="text-sm text-gray-500 dark:text-gray-400 flex items-center gap-1">
                                <lucide-icon [img]="Calendar" class="w-3 h-3"></lucide-icon>
                                {{ property.created_at | date:'dd MMM yyyy' }}
                            </span>
                        </div>
                        <h3 class="text-lg font-bold text-gray-900 dark:text-white group-hover:text-blue-600 transition-colors mb-1">
                            {{ property.title }}
                        </h3>
                        <div class="flex items-center gap-1 text-sm text-gray-500 dark:text-gray-400">
                            <lucide-icon [img]="MapPin" class="w-3.5 h-3.5"></lucide-icon>
                            <span>{{ property.address?.city || 'Dakar' }}, {{ property.address?.address || 'Adresse non spécifiée' }}</span>
                        </div>
                    </div>
                    <div class="text-right">
                        <div class="text-xl font-bold text-gray-900 dark:text-white">
                            {{ property.price | priceFormat }}
                        </div>
                        @if (property.contract_type === 'rent') {
                            <div class="text-sm text-gray-500">/mois</div>
                        }
                    </div>
                </div>

                <p class="text-gray-600 dark:text-gray-300 text-sm line-clamp-2 mb-4 flex-1">
                    {{ property.description }}
                </p>

                <!-- Features -->
                <div class="flex items-center gap-6 py-3 border-t border-gray-100 dark:border-gray-700">
                    <div class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                        <lucide-icon [img]="Bed" class="w-4 h-4"></lucide-icon>
                        <span>{{ property.metadata?.['bedrooms'] || 0 }} Chambres</span>
                    </div>
                    <div class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                        <lucide-icon [img]="Bath" class="w-4 h-4"></lucide-icon>
                        <span>{{ property.metadata?.['bathrooms'] || 0 }} SdB</span>
                    </div>
                    <div class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                        <lucide-icon [img]="Maximize" class="w-4 h-4"></lucide-icon>
                        <span>{{ property.area | areaFormat }}</span>
                    </div>
                </div>

                <!-- Actions -->
                <div class="flex gap-3 mt-4 pt-3">
                    <button (click)="$event.stopPropagation(); scheduleVisit.emit(property)"
                            class="px-4 py-2 text-blue-600 bg-blue-50 hover:bg-blue-100 dark:bg-blue-900/20 dark:text-blue-400 dark:hover:bg-blue-900/40 rounded-lg transition-colors text-sm font-medium flex items-center gap-2">
                        <lucide-icon [img]="Calendar" class="w-4 h-4"></lucide-icon>
                        Visiter
                    </button>
                    <button (click)="$event.stopPropagation(); chat.emit(property)"
                            class="px-4 py-2 text-gray-700 bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 rounded-lg transition-colors text-sm font-medium flex items-center gap-2">
                        Contacter
                    </button>
                    <div class="ml-auto">
                        <span class="text-xs text-blue-600 font-semibold group-hover:translate-x-1 transition-transform inline-flex items-center">
                            Voir détail <lucide-icon [img]="ArrowRight" class="w-3 h-3 ml-1"></lucide-icon>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

// takussan-web/src/components/PropertyCard.tsx
'use client';

import React from 'react';
import Image from 'next/image';
import { Heart, MapPin } from 'lucide-react';
import type { Property } from '@/data/mockData';

export interface PropertyCardProps {
  readonly property: Property;
  readonly className?: string;
}

export function PropertyCard({ property, className }: PropertyCardProps) {
  const isSale = property.transaction === 'sale';

  return (
    <div className={`group cursor-pointer ${className || ''}`}>
      {/* Image Container */}
      <div className="relative aspect-4/3 rounded-xl overflow-hidden mb-5">
        <Image
          src={property.image}
          alt={property.title}
          fill
          className="object-cover group-hover:scale-105 transition-transform duration-500"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw"
        />

        {/* Transaction Badge */}
        <div
          className={`absolute top-4 left-4 text-white text-[10px] font-bold uppercase tracking-wider px-3 py-1.5 rounded-full shadow-md ${
            isSale ? 'bg-[#0050cb]' : 'bg-[#2e7d32]'
          }`}
        >
          {isSale ? 'En Vente' : 'En Location'}
        </div>

        {/* Favorite Button */}
        <button className="absolute top-4 right-4 w-10 h-10 rounded-full bg-white/20 backdrop-blur-md flex items-center justify-center text-white hover:bg-white hover:text-[#0050cb] transition-colors">
          <Heart className="w-5 h-5" />
        </button>
      </div>

      {/* Content */}
      <div className="space-y-2">
        <h3 className="font-bold text-lg text-gray-900">{property.title}</h3>
        <p className="text-[#0050cb] font-bold">{property.price}</p>
        <p className="text-gray-500 text-sm flex items-center gap-1">
          <MapPin className="w-4 h-4" />
          {property.location}
        </p>
        <div className="flex items-center gap-4 pt-2 text-xs font-semibold text-gray-400">
          {property.bedrooms > 0 && (
            <>
              <span>{property.bedrooms} Ch.</span>
              <span className="w-1 h-1 bg-gray-300 rounded-full" />
            </>
          )}
          <span>{property.surface}</span>
          <span className="w-1 h-1 bg-gray-300 rounded-full" />
          <span>{property.feature}</span>
        </div>
      </div>
    </div>
  );
}
